language: go
go: 1.3.3

services:
- rabbitmq

install:
- make deps
- sudo apt-add-repository -y ppa:bcandrea/consul
- sudo apt-get update -qq
- sudo apt-get install -qq consul

before_script:
- "sudo service consul stop || :"
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/consul.pid --make-pidfile --background --exec /usr/bin/consul -- agent -server -bootstrap-expect 1 -data-dir /tmp/consul"

script:
  - make ci
